//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterSimUI {
    
    
    public partial class _Default {
        
        /// <summary>
        /// OutputUserControl3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl3;
        
        /// <summary>
        /// OutputUserControl5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl5;
        
        /// <summary>
        /// OutputUserControl6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl6;
        
        /// <summary>
        /// OutputUserControl7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputUserControl7;
    }
}
